---
- name: tasks for assign1 on slave1
  hosts: slave1
  become: true
  tasks:
    - name: Install Apache2 on slave1
      apt:
        name: apache2
        state: latest

- name: tasks for assign1 on slave2
  hosts: slave2
  become: true
  tasks:
    - name: Install Nginx on slave2
      apt:
        name: nginx
        state: latest
