# Example playbook
---
- name: tasks for assign1 on slave1
  hosts: one
  become: true
  tasks:
    - name: install Apache2
      apt: name=apache2 state=latest

- name: tasks for assign1 on slave2
  hosts: two
  become: true
  tasks:
    - name: install Nginx
      apt: name=nginx state=latest

